---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .

  cli:
    image: ${COMMIT_IMAGE:-local/ddos_deny_list:cli}
    build:
      target: cli
      context: .
    volumes:
      - ./data1/:/usr/src/app/data/
    command: denylist.py $RD_OPTION_TOKEN
    tty: true
https://git-enterprise-jc.onefiserv.net/fts-san/sane/dev-rundeck/ddos_denylist_script.git