---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .

  cli:
    image: ${COMMIT_IMAGE:-local/ddos_deny_list:cli}
    build:
      target: cli
      context: .
    volumes:
      - inventory:/usr/src/app/data/:ro
    command: denylist.py $RD_OPTION_TOKEN $RD_OPTION_SPLUNKTOKEN
    tty: true
  inventory_service:
    image: ${INVENTORY_IMAGE}
    volumes:
      # Requires 'VOLUME /usr/src/app/inventory' in inventory Dockerfile
      - inventory:/usr/src/app/inventory:ro
  
volumes:
  inventory:
